CLIENT_UID = 'your-client-uid'
WEBSOCKET_HOSTNAME = 'your-url'
WEBSOCKET_PORT = 'your-port'
WEBSOCKET_PATH = '/connect/%s' % CLIENT_UID
WEBSOCKET_TLS = False
WEBSOCKET_USER = 'your-websocket-user'
WEBSOCKET_PASSWORD = 'your-password'
WIFI_NETWORK = 'your-wifi-user'
WIFI_PASSWORD = 'your-wifi-password'
RESOURCE_UID = 'your-resource-uid'
LOCK_OPEN_PIN = 26
LOCK_CLOSE_PIN = 27
DOOR_STATUS_PIN = 33
POWER_STATUS_PIN = 34
